name: Tarea programada de eliminación de cuentas

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-old-users:
    runs-on: ubuntu-latest

    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v2

      - name: Hacer solicitud para eliminar cuentas pendientes
        run: |
          response=$(curl -s -w "%{http_code}" -o /dev/null -X DELETE ${{ secrets.API_http }} \
            -H "Authorization: Bearer ${{ secrets.API_PASSWORD }}")
          if [ "$response" -eq 200 ]; then
            echo "Cuentas programadas eliminadas con éxito."
          else
            echo "Error al eliminar cuentas programadas. Código de respuesta: $response"
            exit 1
          fi

      - name: Confirmación de eliminación
        run: echo "Se ha solicitado la eliminación de cuentas programadas."