name: Scheduled Account Deletion Task

on:
  schedule:
    # Runs every day at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  delete-scheduled-accounts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Automatic Account Deletion with Retry
        run: |
          MAX_RETRIES=3
          RETRY_DELAY=10  # segundos
          ATTEMPT=0
          SUCCESS=false

          while [ $ATTEMPT -lt $MAX_RETRIES ]; do
            echo "Attempt $((ATTEMPT+1)) to delete scheduled accounts..."

            response=$(curl -s -o response.json -w "%{http_code}" -X DELETE "${{ secrets.API_HTTP }}" \
              -H "Authorization: Bearer ${{ secrets.API_PASSWORD }}")

            echo "Server response code: $response"
            cat response.json  # Muestra la respuesta completa

            if [ "$response" -eq 200 ]; then
              echo "Scheduled accounts successfully deleted."
              SUCCESS=true
              break
            else
              echo "Error deleting scheduled accounts. Retrying in $RETRY_DELAY seconds..."
              ATTEMPT=$((ATTEMPT+1))
              sleep $RETRY_DELAY
            fi
          done

          if [ "$SUCCESS" = false ]; then
            echo "Failed to delete scheduled accounts after $MAX_RETRIES attempts."
            exit 1
          fi

      - name: Confirmation of Deletion
        run: echo "The request for scheduled account deletion has been completed."