openapi: 3.0.0
info:
  title: "Short-X"
  version: "1.0.0"
  description: | 
    This API allows shortening links and obtaining statistics for them.
    It also provides WebSocket functionality to receive real-time updates:

servers:
  - url: "http://localhost:3500/api"

tags:
  - name: "Authentication"
    description: "Operations related to login, registration, and URL redirection."
  - name: "Administration"
    description: "Administrative operations requiring administrator permissions."
  - name: "User"
    description: "Operations for managing users and their data."
  - name: "URLs"
    description: "Operations to shorten, redirect, and manage URLs."
  - name: "Stats"
    description: "Operations for obtaining statistics of user URLs."

security:
  - bearerAuth: []

paths:
  $ref: './index.yaml'

components:
  $ref: './components/security.yaml'
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  parameters:
    $ref: './components/parameters.yaml'
  requestBodies:
    $ref: './components/requestBodies.yaml'
