  userIdParam:
    name: id
    in: path
    required: true
    description: The ID of the user to retrieve
    schema:
      type: string
      example: "abc123" 

  page:
    name: page
    in: query
    description: "Page number for pagination (default is 1)"
    required: false
    schema:
      type: integer
      example: 1

  limit:
    name: limit
    in: query
    description: "Results per page (default is 10)"
    required: false
    schema:
      type: integer
      example: 10